const { colors } = require('tailwindcss/defaultTheme');

module.exports = {
  theme: {
		transform: { // defaults to this value
      'none': 'none',
    },
    transformOrigin: { // defaults to these values
      't': 'top',
      'tr': 'top right',
      'r': 'right',
      'br': 'bottom right',
      'b': 'bottom',
      'bl': 'bottom left',
      'l': 'left',
      'tl': 'top left',
    },
    translate: { // defaults to {}
      '1/2': '50%',
      'full': '100%',
      'right-up': ['100%', '-100%'],
      '3d': ['40px', '-60px', '-130px'],
    },
    scale: { // defaults to {}
      '90': '0.9',
      '100': '1',
      '105': '1.05',
      '110': '1.1',
      '-100': '-1',
      'stretched-x': ['2', '0.5'],
      'stretched-y': ['0.5', '2'],
      '3d': ['0.5', '1', '2'],
    },
    rotate: { // defaults to {}
      '90': '90deg',
      '180': '180deg',
      '270': '270deg',
      '3d': ['0', '1', '0.5', '45deg'],
    },
    skew: { // defaults to {}
      '-5': '-5deg',
      '5': '5deg',
    },
    perspective: { // defaults to {}
      'none': 'none',
      '250': '250px',
      '500': '500px',
      '750': '750px',
      '1000': '1000px',
    },
    perspectiveOrigin: { // defaults to these values
      't': 'top',
      'tr': 'top right',
      'r': 'right',
      'br': 'bottom right',
      'b': 'bottom',
      'bl': 'bottom left',
      'l': 'left',
      'tl': 'top left',
    },
		fontSize: {
			'xs': '.75rem',
      'sm': '.875rem',
      'tiny': '.875rem',
      'base': '1rem',
      'lg': '1.125rem',
      'xl': '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
      '5xl': '3rem',
      '6xl': '4rem',
      '7xl': '5rem',
      '8xl': '6rem',
		},
		transitionProperty: { // defaults to these values
      'none': 'none',
      'all': 'all',
      'color': 'color',
      'bg': 'background-color',
      'border': 'border-color',
      'colors': ['color', 'background-color', 'border-color'],
      'opacity': 'opacity',
      'transform': 'transform',
      'fill': 'fill',
    },
    transitionDuration: { // defaults to these values
      'default': '250ms',
      '0': '0ms',
      '100': '100ms',
      '250': '250ms',
      '500': '500ms',
      '750': '750ms',
      '1000': '1000ms',
    },
    transitionTimingFunction: { // defaults to these values
      'default': 'ease',
      'linear': 'linear',
      'ease': 'ease',
      'ease-in': 'ease-in',
      'ease-out': 'ease-out',
      'ease-in-out': 'ease-in-out',
    },
    transitionDelay: { // defaults to these values
      'default': '0ms',
      '0': '0ms',
      '100': '100ms',
      '250': '250ms',
      '500': '500ms',
      '750': '750ms',
      '1000': '1000ms',
    },
    willChange: { // defaults to these values
      'auto': 'auto',
      'scroll': 'scroll-position',
      'contents': 'contents',
      'opacity': 'opacity',
      'transform': 'transform',
    },
		inset: {
			'0': 0,
			'full': '100%',
			'-1/2': '-50%',
			'1/2': '50%',
			'-1/10': '-10%',
			'1/10': '10%',
			'-2/10': '-20%',
			'2/10': '20%',
			'-3/10': '-30%',
			'3/10': '30%',
			'-4/10': '-40%',
			'4/10': '40%',
			'-5/10': '-50%',
			'5/10': '50%',
			'-6/10': '-60%',
			'6/10': '60%',
			'-7/10': '-70%',
			'7/10': '70%',
			'-8/10': '-80%',
			'8/10': '80%',
			'-9/10': '-90%',
			'9/10': '90%',
			'-11/10': '-110%',
			'11/10': '110%',
			'10px': '10px',
			'-10px': '-10px',
			'30px': '30px',
			'-30px': '-30px',
			'60px': '60px',
			'-60px': '-60px',
			'100px': '100px',
			'-100px': '-100px',
			'120px': '120px',
			'-120px': '-120px',
			'300px': '300px',
			'-300px': '-300px',
		},
		opacity: {
			'0': '0',
			'10': '.1',
			'20': '.2',
			'30': '.3',
			'40': '.4',
			'50': '.5',
			'60': '.6',
			'70': '.7',
			'80': '.8',
			'90': '.9',
      '100': '1',
		},
		height: {
			'0':	'0',
			'1':	'0.25rem',
			'2':	'0.5rem',
			'3':	'0.75rem',
			'4':	'1rem',
			'5':	'1.25rem',
			'6':	'1.5rem',
			'8':	'2rem',
			'10':	'2.5rem',
			'12':	'3rem',
			'16':	'4rem',
			'20':	'5rem',
			'24':	'6rem',
			'32':	'8rem',
			'40':	'10rem',
			'48':	'12rem',
			'56':	'14rem',
			'64':	'16rem',
			'auto':	'auto',
			'px':	'1px',
			'600px': '600px',
			'full':	'100%',
			'screen':	'100vh',
		},
    colors: {
			black: colors.black,
      white: colors.white,
      gray: colors.gray,
      red: colors.red,
      yellow: colors.yellow,
      green: colors.green,
      blue: colors.blue,
      indigo: colors.indigo,
      purple: colors.purple,
			pink: colors.pink,
			orange: colors.orange,
			'blue-green': ['#3182CE', '#4299E1', '#38B2AC', '#4FD1C5'],
			'blue-shades': ['#2A4365', '#2B6CB0', '#3182CE', '#63B3ED'],
			'blue-shades-dark': ['#2A4365', '#2A4365', '#2B6CB0'],
			'blue-shades-ultra-dark': ['#2A4365', '#2C5282'],
    },
		fill: {
			black: colors.black,
      white: colors.white,
      gray: colors.gray,
      red: colors.red,
      yellow: colors.yellow,
      green: colors.green,
      blue: colors.blue,
      indigo: colors.indigo,
      purple: colors.purple,
      'current': 'currentColor',
		},
		stroke: {
			black: colors.black,
      white: colors.white,
      gray: colors.gray,
      red: colors.red,
      yellow: colors.yellow,
      green: colors.green,
      blue: colors.blue,
      indigo: colors.indigo,
      purple: colors.purple,
		},
		linearGradients: theme => ({
      colors: theme('colors'),
    }),
    radialGradients: theme => ({
      colors: theme('colors'),
    }),
    conicGradients: theme => ({
      colors: theme('colors'),
    }),
    extend: {}
  },
  variants: {
		transitionProperty: ['responsive'],
    transitionDuration: ['responsive'],
    transitionTimingFunction: ['responsive'],
    transitionDelay: ['responsive'],
    willChange: ['responsive'],
		transform: ['responsive'],
    transformOrigin: ['responsive'],
    translate: ['responsive'],
    scale: ['responsive, hover'],
    rotate: ['responsive'],
    skew: ['responsive'],
    perspective: ['responsive'],
    perspectiveOrigin: ['responsive'],
    transformStyle: ['responsive'],
    backfaceVisibility: ['responsive'],
    transformBox: ['responsive'],
		mixBlendMode: ['responsive'],
    backgroundBlendMode: ['responsive'],
    isolation: ['responsive'],
		fill: ['responsive, hover'],
		stroke: ['responsive, hover'],
	},
  plugins: [
		require('tailwindcss-gradients')(),
		require('tailwindcss-transitions')(),
		require('tailwindcss-transforms')({
      '3d': false, // defaults to false
    }),
		require('tailwindcss-blend-mode')(),
	],
}
